Add empty, resize, dup
metagraph-dev/mlir-graphblas pull request #45
Opened 2021-04-29 04:59 UTC by eriknw

The if-elif-else structure in Cython is pretty annoying, but ¯\_(ツ)_/¯

Also, these required adding to the classes in C.  Hopefully this is okay ¯\_(ツ)_/¯

@jim22k, does this satisfy your requests?

2021-04-30 01:20 UTC, jim22k requested changes
I sent you an email with details. Essentially, I need an overhaul of `resize` because sparsity makes things more complicated than one might like.

2021-04-30 16:30 UTC, eriknw commented
Updated.

2021-04-30 23:27 UTC, eriknw commented
New functions added.  I need to add tests for them.

Jim, if they work for you, then we can probably remove `empty_mlir_sparse_tensor_fast` and `empty_mlir_sparse_tensor_safe`.

2021-05-04 16:47 UTC, jim22k approved these changes

2021-05-04 16:53 UTC, jim22k approved these changes

2021-05-04 17:59 UTC, merged